/**
 * Archetype catalogue — the "DNA" of every world kind.
 *
 * Each archetype fully defines a world's look: palette, terrain shape,
 * which props spawn, and the ambient particle field. Adding a new world
 * type is just appending an entry here + the name syllable banks.
 */

import type { ArchetypeDef, ArchetypeId, TimeOfDay } from "./types";

export const ARCHETYPES: Record<ArchetypeId, ArchetypeDef> = {
  verdant: {
    id: "verdant",
    label: "Verdant Wilds",
    tagline: "Lush forests, soft mist, sun-dappled groves.",
    hue: 140,
    palette: {
      skyTop: "#3a8d5a",
      skyBottom: "#cfe8d0",
      sun: "#fff3d6",
      fog: "#bcd9c0",
      fogDensity: 0.018,
      ground: "#4f7a3a",
      groundAccent: "#6e9f4a",
      water: "#2f7fa8",
      foliage: "#2f7d3a",
      emissive: "#9bff7a",
    },
    terrain: { heightScale: 14, frequency: 0.05, octaves: 5, ridged: false, waterLevel: 2.4 },
    props: [
      ["pine", 4],
      ["broadleaf", 5],
      ["rock", 1.2],
    ],
    particles: "pollen",
    names: {
      prefixes: ["Old", "Green", "Whisper", "Moss", "Thorn", "Ember"],
      roots: ["Vale", "Hollow", "Reach", "Glen", "Mere"],
      suffixes: ["Wood", "Thicket", "Grove", "Copse", "Glade"],
    },
  },
  crystal: {
    id: "crystal",
    label: "Crystal Spires",
    tagline: "Faceted towers refracting prismatic light.",
    hue: 280,
    palette: {
      skyTop: "#2a1a4a",
      skyBottom: "#7b5fd0",
      sun: "#e0c8ff",
      fog: "#6a4ea8",
      fogDensity: 0.022,
      ground: "#3a2a5a",
      groundAccent: "#7a5fb0",
      water: "#5a3f9a",
      foliage: "#b58cff",
      emissive: "#d8b4ff",
    },
    terrain: { heightScale: 26, frequency: 0.045, octaves: 4, ridged: true, waterLevel: null },
    props: [
      ["crystal", 6],
      ["monolith", 1.5],
      ["rock", 1],
    ],
    particles: "spores",
    names: {
      prefixes: ["Prism", "Facet", "Shard", "Lucent", "Opal"],
      roots: ["Halls", "Spire", "Lattice", "Crown", "Citadel"],
      suffixes: ["of Light", "Ascendant", "Eternal", "Veined"],
    },
  },
  volcanic: {
    id: "volcanic",
    label: "Volcanic Wastes",
    tagline: "Smouldering calderas, rivers of fire.",
    hue: 18,
    palette: {
      skyTop: "#2a0a0a",
      skyBottom: "#7a1a0a",
      sun: "#ff5a2a",
      fog: "#5a1a0a",
      fogDensity: 0.03,
      ground: "#3a1f1a",
      groundAccent: "#6a2a1a",
      water: "#ff4a1a",
      foliage: "#2a1a14",
      emissive: "#ff5a1a",
    },
    terrain: { heightScale: 22, frequency: 0.05, octaves: 5, ridged: true, waterLevel: null },
    props: [
      ["lava", 3],
      ["rock", 3],
      ["pillar", 1.5],
      ["geyser", 1],
    ],
    particles: "embers",
    names: {
      prefixes: ["Ash", "Ember", "Cinder", "Magma", "Soot"],
      roots: ["Wastes", "Caldera", "Furnace", "Reach", "Crags"],
      suffixes: ["of Fire", "Burning", "the Scorched", "Smouldering"],
    },
  },
  tundra: {
    id: "tundra",
    label: "Frozen Tundra",
    tagline: "Endless white, biting wind, aurora overhead.",
    hue: 190,
    palette: {
      skyTop: "#0a1a3a",
      skyBottom: "#3a7ad0",
      sun: "#dceaff",
      fog: "#bcd0e8",
      fogDensity: 0.024,
      ground: "#dfeaf2",
      groundAccent: "#bcd0e0",
      water: "#1a3a6a",
      foliage: "#9fb8c8",
      emissive: "#9fd8ff",
    },
    terrain: { heightScale: 10, frequency: 0.04, octaves: 4, ridged: false, waterLevel: null },
    props: [
      ["iceberg", 4],
      ["rock", 1.5],
      ["pine", 0.8],
    ],
    particles: "snow",
    names: {
      prefixes: ["Pale", "Frost", "Bitter", "White", "Howling"],
      roots: ["Expanse", "Tundra", "Steppe", "Fields", "Reach"],
      suffixes: ["of Ice", "Eternal", "White", "Frozen"],
    },
  },
  xenoflora: {
    id: "xenoflora",
    label: "Xenoflora Bloom",
    tagline: "Alien bioluminescent jungle on another world.",
    hue: 300,
    palette: {
      skyTop: "#1a0a2a",
      skyBottom: "#5a1a7a",
      sun: "#c878ff",
      fog: "#4a1a6a",
      fogDensity: 0.028,
      ground: "#2a1a3a",
      groundAccent: "#5a2a7a",
      water: "#7a2acf",
      foliage: "#d060ff",
      emissive: "#ff8aff",
    },
    terrain: { heightScale: 18, frequency: 0.05, octaves: 5, ridged: false, waterLevel: 2 },
    props: [
      ["mushroom", 4],
      ["broadleaf", 2],
      ["arch", 1],
      ["monolith", 0.8],
    ],
    particles: "spores",
    names: {
      prefixes: ["Xeno", "Drift", "Pulse", "Bloom", "Void"],
      roots: ["Bloom", "Biome", "Garden", "Thicket", "Reach"],
      suffixes: ["of Stars", "Awakened", "Primeval", "Unmapped"],
    },
  },
  dunes: {
    id: "dunes",
    label: "Sun-Scorched Dunes",
    tagline: "Rolling amber sand under a copper sky.",
    hue: 40,
    palette: {
      skyTop: "#c8702a",
      skyBottom: "#ffd89a",
      sun: "#fff0c0",
      fog: "#e8b878",
      fogDensity: 0.02,
      ground: "#d8a85a",
      groundAccent: "#e8c078",
      water: "#3a8acf",
      foliage: "#8a6a3a",
      emissive: "#ffd070",
    },
    terrain: { heightScale: 16, frequency: 0.035, octaves: 3, ridged: false, waterLevel: null },
    props: [
      ["cactus", 3],
      ["rock", 2],
      ["arch", 0.8],
    ],
    particles: "dust",
    names: {
      prefixes: ["Amber", "Dust", "Sun", "Mirage", "Gold"],
      roots: ["Dunes", "Erg", "Wastes", "Sea", "Reach"],
      suffixes: ["of Sand", "Endless", "Sunbaked", "Wind-carved"],
    },
  },
  islands: {
    id: "islands",
    label: "Floating Islands",
    tagline: "Skybound landmasses drifting above the clouds.",
    hue: 205,
    palette: {
      skyTop: "#2a6acf",
      skyBottom: "#a8d8ff",
      sun: "#ffffff",
      fog: "#bcdcff",
      fogDensity: 0.012,
      ground: "#4a7a4a",
      groundAccent: "#6e9f5a",
      water: "#9fd8ff",
      foliage: "#3a8d5a",
      emissive: "#ffffff",
    },
    terrain: { heightScale: 20, frequency: 0.06, octaves: 4, ridged: false, waterLevel: null },
    props: [
      ["broadleaf", 4],
      ["rock", 2],
      ["arch", 1.5],
      ["pillar", 1],
    ],
    particles: "leaves",
    names: {
      prefixes: ["Drift", "Sky", "Buoyant", "Cloud", "Aero"],
      roots: ["Archipelago", "Drift", "Skies", "Arches", "Reach"],
      suffixes: ["Ascendant", "of Clouds", "Afloat", "Boundless"],
    },
  },
  reef: {
    id: "reef",
    label: "Abyssal Reef",
    tagline: "Kelp towers and lantern-fish in the deep.",
    hue: 175,
    palette: {
      skyTop: "#0a2a3a",
      skyBottom: "#1a5a6a",
      sun: "#5af0d0",
      fog: "#1a4a5a",
      fogDensity: 0.04,
      ground: "#1a3a4a",
      groundAccent: "#2a5a6a",
      water: "#1a4a6a",
      foliage: "#2acfb0",
      emissive: "#5affd0",
    },
    terrain: { heightScale: 12, frequency: 0.04, octaves: 4, ridged: false, waterLevel: null },
    props: [
      ["coral", 5],
      ["pillar", 2],
      ["rock", 1.5],
    ],
    particles: "bubbles",
    names: {
      prefixes: ["Deep", "Tidal", "Kelp", "Lantern", "Abyss"],
      roots: ["Reef", "Trench", "Abyss", "Shelf", "Sound"],
      suffixes: ["of Tides", "Sunken", "Bioluminous", "Endless"],
    },
  },
  cyber: {
    id: "cyber",
    label: "Neon Grid",
    tagline: "Synthwave sprawl, holograms, endless rain.",
    hue: 320,
    palette: {
      skyTop: "#1a0a2a",
      skyBottom: "#cf2a8a",
      sun: "#ff5acf",
      fog: "#5a1a4a",
      fogDensity: 0.026,
      ground: "#1a0a1a",
      groundAccent: "#3a0a2a",
      water: "#2a1a4a",
      foliage: "#cf2acf",
      emissive: "#ff5acf",
    },
    terrain: { heightScale: 6, frequency: 0.08, octaves: 3, ridged: false, waterLevel: null },
    props: [
      ["tower", 6],
      ["neonTree", 2],
      ["monolith", 1],
    ],
    particles: "data",
    names: {
      prefixes: ["Neon", "Synth", "Glitch", "Chrome", "Pulse"],
      roots: ["Grid", "District", "Sprawl", "Nexus", "Core"],
      suffixes: ["2099", "Prime", "Overdrive", "Wired"],
    },
  },
  nebula: {
    id: "nebula",
    label: "Nebula Void",
    tagline: "Drifting through a star-swaddled nursery.",
    hue: 260,
    palette: {
      skyTop: "#0a0a2a",
      skyBottom: "#2a1a5a",
      sun: "#ffffff",
      fog: "#1a1a3a",
      fogDensity: 0.014,
      ground: "#1a1a3a",
      groundAccent: "#3a2a6a",
      water: "#2a2a6a",
      foliage: "#8a7acf",
      emissive: "#c8b8ff",
    },
    terrain: { heightScale: 8, frequency: 0.05, octaves: 3, ridged: false, waterLevel: null },
    props: [
      ["monolith", 3],
      ["crystal", 2],
      ["arch", 1.5],
      ["pillar", 1],
    ],
    particles: "stardust",
    names: {
      prefixes: ["Void", "Star", "Drift", "Celestial", "Nova"],
      roots: ["Drift", "Nursery", "Expanse", "Reach", "Veil"],
      suffixes: ["of Stars", "Eternal", "Unmapped", "Primeval"],
    },
  },
  mushroom: {
    id: "mushroom",
    label: "Mushroom Kingdom",
    tagline: "Gigantic canopied fungi humming low chords.",
    hue: 330,
    palette: {
      skyTop: "#3a1a2a",
      skyBottom: "#cf7a9a",
      sun: "#ffd0e0",
      fog: "#9a5a7a",
      fogDensity: 0.022,
      ground: "#4a3a2a",
      groundAccent: "#7a5a3a",
      water: "#5a3a5a",
      foliage: "#cf5a8a",
      emissive: "#ff9acf",
    },
    terrain: { heightScale: 12, frequency: 0.04, octaves: 4, ridged: false, waterLevel: 1.5 },
    props: [
      ["mushroom", 6],
      ["broadleaf", 1.5],
      ["rock", 1],
    ],
    particles: "spores",
    names: {
      prefixes: ["Spore", "Cap", "Gilled", "Mycelium", "Toad"],
      roots: ["Canopy", "Ring", "Grove", "Thicket", "Reach"],
      suffixes: ["of Caps", "Humming", "Boundless", "Deep-rooted"],
    },
  },
  savannah: {
    id: "savannah",
    label: "Sunbaked Plains",
    tagline: "Amber grass sea beneath baobab shadows.",
    hue: 60,
    palette: {
      skyTop: "#3a6acf",
      skyBottom: "#ffd89a",
      sun: "#fff0c0",
      fog: "#e8d0a0",
      fogDensity: 0.016,
      ground: "#b89a4a",
      groundAccent: "#d8b868",
      water: "#2a8acf",
      foliage: "#8a7a3a",
      emissive: "#ffe090",
    },
    terrain: { heightScale: 8, frequency: 0.03, octaves: 3, ridged: false, waterLevel: null },
    props: [
      ["broadleaf", 3],
      ["rock", 2],
      ["pillar", 0.6],
      ["cactus", 0.5],
    ],
    particles: "dust",
    names: {
      prefixes: ["Amber", "Vast", "Sun", "Golden", "Dry"],
      roots: ["Plains", "Veldt", "Savannah", "Range", "Steppe"],
      suffixes: ["of Grass", "Boundless", "Sunlit", "Wide"],
    },
  },
};

export const ARCHETYPE_LIST = Object.values(ARCHETYPES);

/** Time-of-day overlays that tweak sun + fog for the same world. */
export const TIME_OF_DAY: Record<
  TimeOfDay,
  { sunIntensity: number; ambient: number; sunAngle: number; label: string; icon: string }
> = {
  dawn: { sunIntensity: 1.4, ambient: 0.55, sunAngle: 0.12, label: "Dawn", icon: "🌅" },
  noon: { sunIntensity: 2.2, ambient: 0.85, sunAngle: 0.45, label: "Noon", icon: "☀️" },
  dusk: { sunIntensity: 1.1, ambient: 0.45, sunAngle: 0.08, label: "Dusk", icon: "🌇" },
  night: { sunIntensity: 0.25, ambient: 0.22, sunAngle: -0.1, label: "Night", icon: "🌙" },
};
