/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OsRouteImport } from './routes/os'
import { Route as AwakeningRouteImport } from './routes/awakening'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPaddleWebhookRouteImport } from './routes/api/paddle-webhook'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWebResearchRouteImport } from './routes/_authenticated/web-research'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'
import { Route as AuthenticatedSingularityRouteImport } from './routes/_authenticated/singularity'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedMultiverseRouteImport } from './routes/_authenticated/multiverse'
import { Route as AuthenticatedMicRouteImport } from './routes/_authenticated/mic'
import { Route as AuthenticatedImageRouteImport } from './routes/_authenticated/image'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGameBuilderRouteImport } from './routes/_authenticated/game-builder'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const AwakeningRoute = AwakeningRouteImport.update({
  id: '/awakening',
  path: '/awakening',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaddleWebhookRoute = ApiPaddleWebhookRouteImport.update({
  id: '/api/paddle-webhook',
  path: '/api/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebResearchRoute =
  AuthenticatedWebResearchRouteImport.update({
    id: '/web-research',
    path: '/web-research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSingularityRoute =
  AuthenticatedSingularityRouteImport.update({
    id: '/singularity',
    path: '/singularity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMultiverseRoute = AuthenticatedMultiverseRouteImport.update({
  id: '/multiverse',
  path: '/multiverse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMicRoute = AuthenticatedMicRouteImport.update({
  id: '/mic',
  path: '/mic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageRoute = AuthenticatedImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGameBuilderRoute =
  AuthenticatedGameBuilderRouteImport.update({
    id: '/game-builder',
    path: '/game-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/awakening': typeof AwakeningRoute
  '/os': typeof OsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/world': typeof WorldRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/code': typeof AuthenticatedCodeRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/game-builder': typeof AuthenticatedGameBuilderRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/image': typeof AuthenticatedImageRoute
  '/mic': typeof AuthenticatedMicRoute
  '/multiverse': typeof AuthenticatedMultiverseRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/singularity': typeof AuthenticatedSingularityRoute
  '/video': typeof AuthenticatedVideoRoute
  '/web-research': typeof AuthenticatedWebResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/images': typeof ApiImagesRoute
  '/api/paddle-webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/awakening': typeof AwakeningRoute
  '/os': typeof OsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/world': typeof WorldRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/code': typeof AuthenticatedCodeRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/game-builder': typeof AuthenticatedGameBuilderRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/image': typeof AuthenticatedImageRoute
  '/mic': typeof AuthenticatedMicRoute
  '/multiverse': typeof AuthenticatedMultiverseRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/singularity': typeof AuthenticatedSingularityRoute
  '/video': typeof AuthenticatedVideoRoute
  '/web-research': typeof AuthenticatedWebResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/images': typeof ApiImagesRoute
  '/api/paddle-webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/awakening': typeof AwakeningRoute
  '/os': typeof OsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/world': typeof WorldRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/game-builder': typeof AuthenticatedGameBuilderRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/image': typeof AuthenticatedImageRoute
  '/_authenticated/mic': typeof AuthenticatedMicRoute
  '/_authenticated/multiverse': typeof AuthenticatedMultiverseRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/singularity': typeof AuthenticatedSingularityRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
  '/_authenticated/web-research': typeof AuthenticatedWebResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/images': typeof ApiImagesRoute
  '/api/paddle-webhook': typeof ApiPaddleWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/awakening'
    | '/os'
    | '/reset-password'
    | '/world'
    | '/billing'
    | '/chat'
    | '/code'
    | '/documents'
    | '/game-builder'
    | '/history'
    | '/home'
    | '/image'
    | '/mic'
    | '/multiverse'
    | '/prompts'
    | '/settings'
    | '/singularity'
    | '/video'
    | '/web-research'
    | '/api/chat'
    | '/api/images'
    | '/api/paddle-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/awakening'
    | '/os'
    | '/reset-password'
    | '/world'
    | '/billing'
    | '/chat'
    | '/code'
    | '/documents'
    | '/game-builder'
    | '/history'
    | '/home'
    | '/image'
    | '/mic'
    | '/multiverse'
    | '/prompts'
    | '/settings'
    | '/singularity'
    | '/video'
    | '/web-research'
    | '/api/chat'
    | '/api/images'
    | '/api/paddle-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/awakening'
    | '/os'
    | '/reset-password'
    | '/world'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/code'
    | '/_authenticated/documents'
    | '/_authenticated/game-builder'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/image'
    | '/_authenticated/mic'
    | '/_authenticated/multiverse'
    | '/_authenticated/prompts'
    | '/_authenticated/settings'
    | '/_authenticated/singularity'
    | '/_authenticated/video'
    | '/_authenticated/web-research'
    | '/api/chat'
    | '/api/images'
    | '/api/paddle-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AwakeningRoute: typeof AwakeningRoute
  OsRoute: typeof OsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WorldRoute: typeof WorldRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImagesRoute: typeof ApiImagesRoute
  ApiPaddleWebhookRoute: typeof ApiPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awakening': {
      id: '/awakening'
      path: '/awakening'
      fullPath: '/awakening'
      preLoaderRoute: typeof AwakeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paddle-webhook': {
      id: '/api/paddle-webhook'
      path: '/api/paddle-webhook'
      fullPath: '/api/paddle-webhook'
      preLoaderRoute: typeof ApiPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/web-research': {
      id: '/_authenticated/web-research'
      path: '/web-research'
      fullPath: '/web-research'
      preLoaderRoute: typeof AuthenticatedWebResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/singularity': {
      id: '/_authenticated/singularity'
      path: '/singularity'
      fullPath: '/singularity'
      preLoaderRoute: typeof AuthenticatedSingularityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multiverse': {
      id: '/_authenticated/multiverse'
      path: '/multiverse'
      fullPath: '/multiverse'
      preLoaderRoute: typeof AuthenticatedMultiverseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mic': {
      id: '/_authenticated/mic'
      path: '/mic'
      fullPath: '/mic'
      preLoaderRoute: typeof AuthenticatedMicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image': {
      id: '/_authenticated/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof AuthenticatedImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game-builder': {
      id: '/_authenticated/game-builder'
      path: '/game-builder'
      fullPath: '/game-builder'
      preLoaderRoute: typeof AuthenticatedGameBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGameBuilderRoute: typeof AuthenticatedGameBuilderRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedImageRoute: typeof AuthenticatedImageRoute
  AuthenticatedMicRoute: typeof AuthenticatedMicRoute
  AuthenticatedMultiverseRoute: typeof AuthenticatedMultiverseRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSingularityRoute: typeof AuthenticatedSingularityRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
  AuthenticatedWebResearchRoute: typeof AuthenticatedWebResearchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGameBuilderRoute: AuthenticatedGameBuilderRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedImageRoute: AuthenticatedImageRoute,
  AuthenticatedMicRoute: AuthenticatedMicRoute,
  AuthenticatedMultiverseRoute: AuthenticatedMultiverseRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSingularityRoute: AuthenticatedSingularityRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
  AuthenticatedWebResearchRoute: AuthenticatedWebResearchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AwakeningRoute: AwakeningRoute,
  OsRoute: OsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WorldRoute: WorldRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImagesRoute: ApiImagesRoute,
  ApiPaddleWebhookRoute: ApiPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
